### ISSUE TITLE
【开源自荐】基于Canvas的开源版"稿定设计"

### ISSUE THREAD

**Issue by more-strive** [tnfe/TNT-Weekly#138]
### yft-design
一款美观且功能强大的在线设计工具，具备海报设计和图片编辑功能。适用于多种场景，如海报生成、电商产品图制作、文章长图设计、视频/公众号封面编辑  
Demo:  https://yft.design
Github: https://github.com/dromara/yft-design
- 支持pdf解析
- 支持psd解析
- 支持抠图功能

### 编辑页面
![image](https://github.com/tnfe/TNT-Weekly/assets/113762408/2a4a3c76-c790-41ef-a0ba-5a8b7c28b879)
### psd解析
![psd-parse](https://github.com/tnfe/TNT-Weekly/assets/113762408/21a6d64d-7497-419c-9a48-d3e94f61c2ff)
### pdf解析
![pdf-parse](https://github.com/tnfe/TNT-Weekly/assets/113762408/80a6fd2d-e3a9-4a92-9579-fcff9513a86e)

**Comment by q269384828** [comment]
牛的

**Comment by more-strive** [comment]
> 牛的

谢谢肯定啊，欢迎一起来维护，让免费设计

**Comment by CodeGetters** [comment]
牛的

**Comment by more-strive** [comment]
> 牛的

谢谢肯定哈，给个star支持啊

**Comment by CodeGetters** [comment]
> > 牛的
> 
> 谢谢肯定哈，给个star支持啊

star了😂

**Comment by chengxiaoming** [comment]
你好，来信收到。

**Comment by Winston131** [comment]
你好，邮件已收到，我会尽快给您回复。谢谢

**Comment by CodeGetters** [comment]
Cool
