### ISSUE TITLE
推荐前端Mock工具——Mokia

### ISSUE THREAD

**Issue by varHarrie** [tnfe/TNT-Weekly#78]
**源码仓库**：https://github.com/varHarrie/mokia
**文档链接**：https://varharrie.github.io/mokia/

**简介**：一个开箱即用的API模拟服务器，帮助快速创建后端原型和数据模拟。

**特性**：
- 数据模拟：提供大量 mock 函数，支持生成数字、文本、日期、颜色、图片等，还支持嵌套、组合等结构复杂的数据。
- 本地服务器：开发者无需关注服务器逻辑，通过命令就可以快速启动一个拟真的本地 mock 服务器。
- 配置文件：基于JavaScript的配置文件，配合IDE的支持，可以很轻松地进行管理和维护。

**用法**：

创建入口文件（index.js）：

```javascript
module.exports = {
  port: 3000,
  'GET /users'() {
    return this.list(() => ({ id: this.uuid(), name: this.fullName() }));
  },
  'GET /users/:id'(req) {
    return { id: req.params.id, name: this.fullName() };
  },
};
```

启动本地服务器：

```bash
npx mokia index.js --watch
```

打开浏览器进入http://localhost:3000/users (opens new window)，你就能看到响应信息了。

**Comment by JN-H** [comment]
收，干得漂亮 ：）
