### ISSUE TITLE
【开源自荐】一个轻量的 Web IDE UI 框架 - Molecule

### ISSUE THREAD

**Issue by AndyZjy** [tnfe/TNT-Weekly#80]
<img src="https://user-images.githubusercontent.com/22025154/146745870-19602cc4-2dc1-4cc5-8a0a-c2ab4dc8f766.png" width="20%" height="20%" alt="watchman-logo" style="max-width: 100%;margin: 0 auto;">

 <h1 style="text-align: center">Molecule</h1>
 <h3>一个轻量的 Web IDE UI 框架</h3>

[Molecule](https://github.com/DTStack/molecule) 是一款受 **VSCode** 启发，使用 **React.js** 构建的 **Web IDE UI** 框架。我们设计了类似 VSCode 的**扩展**（Extension)机制，可以帮助我们使用 React 组件快速完成对 Workbench 的自定义。Molecule 与 **React** 项目集成非常方便，我们已经在 [DTStack](https://www.dtstack.com/) 多个产品、项目中使用。

[在线预览](https://dtstack.github.io/molecule-examples/#/)

## 核心功能

-   内置 React 版本的 Visual Studio Code **Workbench** UI
-   基本兼容 Visual Studio Code 的 **ColorTheme**
-   支持使用 React 组件自定义 **Workbench** UI 样式
-   内置 Monaco Editor **Command Palette**、**Keybinding**等模块，并支持扩展
-   支持 **i18n**，内置简体中文、English 2 种语言
-   内置一个简单的 **Settings** 模块，支持在线编辑修改以及扩展
-   内置默认的 **Explorer**, **Search** 等组件，并支持扩展
-   Typescript 支持

## 与其他开源的 Web IDE 的区别？
Molecule 只是一个单纯的 Web IDE UI 交互框架，不涉及例如文件系统、版本管理、 LSP、DAP、Terminal 等更复杂的 IDE 功能，需要开发者自己手动实现
基于 React.js 的组件库，更好的 UI 自定义能力, React.js 应用无缝接入
基本兼容了 VS Code 上千种 ColorTheme 扩展

**Comment by JN-H** [comment]
👍  安排：）
