### ISSUE TITLE
【推荐】AntV/S2 基于Canvas的高性能多维分析表格

### ISSUE THREAD

**Issue by qubaomingg** [tnfe/TNT-Weekly#88]
源码仓库：https://github.com/antvis/S2
文档链接：https://juejin.cn/post/7081548620033425421/

简介：S2 是多维交叉分析领域的表格解决方案，数据驱动视图，提供底层核心库、基础组件库、业务场景库，具备自由扩展的能力，让开发者既能开箱即用，也能基于自身场景自由发挥。

**Comment by JN-H** [comment]
不错，感谢推荐：）
